backend:
  name: git-gateway
  branch: main
  squash_merges: true
  commit_messages:
    create: 'Create {{collection}} “{{slug}}”'
    update: 'Update {{collection}} “{{slug}}”'
    delete: 'Delete {{collection}} “{{slug}}”'
    uploadMedia: '[skip ci] Upload “{{path}}”'
    deleteMedia: '[skip ci] Delete “{{path}}”'

media_folder: static/img
public_folder: /img

collections:
  - name: tools
    label: Tools
    folder: content/tools
    media_folder: /static/img/tools
    public_folder: /img/tools
    create: true
    editor:
      preview: false
    slug: '{{tool}}'
    fields:
      - {label: Tool, name: tool, widget: string}
      - {label: Icon, name: icon, widget: image}

  - name: repos
    label: Repositories
    folder: content/repos
    create: true
    editor:
      preview: false
    slug: '{{repo}}'
    fields:
      - {label: Repository, name: repo, widget: string}
      - {label: Link, name: link, widget: string}
      - {label: Tools, name: tools, widget: relation,
          collection: tools, searchFields: ['tool'],
          displayFields: ['tool'], multiple: true}

  - name: posts
    label: Blog Posts
    folder: content/posts
    create: true
    editor:
      preview: false
    slug: '{{title}}'
    fields:
      - {label: Title, name: title, widget: string}
      - {label: Link, name: link, widget: string}

  - name: employers
    label: Employers
    folder: content/employers
    media_folder: /static/img/employers
    public_folder: /img/employers
    create: true
    editor:
        preview: false
    slug: '{{employer}}'
    fields:
      - {label: Employer, name: employer, widget: string}
      - {label: Logo, name: logo, widget: image}

  - name: jobs
    label: Work Experiences
    folder: content/jobs
    create: true
    editor:
      preview: false
    slug: '{{employer}} - {{position}}'
    fields:
      - {label: Employer, name: employer, widget: relation,
          collection: employers, searchFields: ['employer'],
          displayFields: ['employer'], multiple: true}
      - {label: Position, name: position, widget: string}
      - {label: Start, name: start, widget: string}
      - {label: End, name: end, widget: string}

  - name: socials
    label: Socials
    folder: content/socials
    media_folder: /static/img/socials
    public_folder: /img/socials
    create: true
    editor:
      preview: false
    slug: '{{name}}'
    fields:
      - {label: Name, name: name, widget: string}
      - {label: Icon, name: icon, widget: image}
      - {label: Link, name: link, widget: string}
