backend:
  name: git-gateway
  branch: main
  squash_merges: true
  commit_messages:
    create: 'Create {{collection}} “{{slug}}”'
    update: 'Update {{collection}} “{{slug}}”'
    delete: 'Delete {{collection}} “{{slug}}”'
    uploadMedia: '[skip ci] Upload “{{path}}”'
    deleteMedia: '[skip ci] Delete “{{path}}”'

media_folder: static/img
public_folder: /img

collections:
  - name: tools
    label: Tools
    folder: content/tools
    media_folder: /static/img/tools
    public_folder: /img/tools
    create: true
    editor:
      preview: false
    slug: '{{tool}}'
    fields:
      - {label: Tool, name: tool, widget: string}
      - {label: Icon, name: icon, widget: image}

  - name: repos
    label: Repositories
    folder: content/repos
    create: true
    editor:
      preview: false
    slug: '{{repo}}'
    fields:
      - {label: Repository, name: repo, widget: string}
      - {label: Link, name: link, widget: string}
      - {label: Tools, name: tools, widget: relation,
          collection: tools, searchFields: ['tool'],
          displayFields: ['tool'], multiple: true}

  - name: posts
    label: Blog Posts
    folder: content/posts
    create: true
    editor:
      preview: false
    slug: '{{title}}'
    fields:
      - {label: Title, name: title, widget: string}
      - {label: Link, name: link, widget: string}
